### ISSUE TITLE
Add text and make /connect page pretty

### ISSUE THREAD

**Issue by jhthorsen** [mojoconf/MCT#12]
I'm not sure what to write, but right now http://localhost:3000/connect is not very nice. "Some message which will make the visitor think this is a good idea" need to be replaced with some actual description of why we decide to use Eventbrite and why it's a good idea (required) for the user to connect.

I also think the whole page is misplaced compared to the landing page: The text is way too far to the left, compared to the text on the landing page.

Maybe you want to add a top-image? Maybe just re-use the same as from the landing page?

The "Connect" button need to be "Connect and register" or something. And it needs to be a lot bigger and have a color (blue?) which makes it pop out and make me want to click it. Right now it's way to easy to miss.

**Comment by tempire** [comment]
What is the purpose of the page, in terms of the user flow?

**Comment by jhthorsen** [comment]
The purpose is that I don't like a Register (Connect) button to take you directly to Eventbrite. Users (including myself) get confused when redirected to a completely different page to do register, without the proper introduction first.

A direct link to Eventbrite (without the /connect page in between) makes me wonder if someone has hacked mojoconf.com and replaced links.

Login on the other hand is different, since the user should then already be familiar with Eventbrite.

**Comment by tempire** [comment]
Oh, I see what you’re saying. Here’s what I’m envisioning - just an embedded order form, like cocoaconf has:

http://cocoaconf.com/dc-2015/register http://cocoaconf.com/dc-2015/register

**Comment by jhthorsen** [comment]
But will "register" also do connect? I'm suggesting this:
1. Click on "Register" button (in main nav bar)
2. See the /connect page with some information
3. Click on "Connect" button
4. Go through register process on Eventbrite (or simply connect)
5. Go back to an embedded order form on mojoconf.com

I think it's important to connect the user first and then make them register. I don't think the flow will make sense if you register to the event (order) first and then connect. I think it's a good idea to connect all users, so they exist in both the eventbrite and MCT database.

**Comment by tempire** [comment]
I strongly disagree. This is one of the problems with ACT - it prioritizes the development process over the user experience - 50 steps before I can just get my conference ticket.

As a customer, why do I care about some connect process? What does that even mean? Just give me my ticket!!!!!11!1

**Comment by jhthorsen** [comment]
Hehe. I was hoping for your exact response :+1: 

So, most users only care about getting the ticket, right? But the process of submitting a talk require OAuth2 connect?

So how do we solve this? I'm suggesting "Login" works like it does now (sends you to Eventbrite connect page), while "Register" sends you to "/register" instead of "/connect" where we have the embedded form?

**Comment by tempire** [comment]
Ok. That’s sensible; I understand where you’re coming from now.

Agreed on all points.

**Comment by tempire** [comment]
We can also use these resources:

http://developer.eventbrite.com/doc/widgets http://developer.eventbrite.com/doc/widgets

**Comment by jhthorsen** [comment]
I didn't get "I understand where you’re coming from now"...

Anyway, regarding "resources": Do you mean we should use http://developer.eventbrite.com/doc/widgets/#ticket on the "/register" page?

``` html
<div style="width:100%; text-align:left;" >
  <iframe src="http://www.eventbrite.com/tickets-external?eid=15825231694&ref=etckt&v=2" frameborder="0" height="256" width="100%" vspace="0" hspace="0" marginheight="5" marginwidth="5" scrolling="auto" allowtransparency="true"></iframe>
</div>
```

If so: :+1:

**Comment by tempire** [comment]
Yes

**Comment by jhthorsen** [comment]
I'm stealing this issue for now. Going to make the flow that we described for /connect. Making a new issue regarding /register: #14.

**Comment by jhthorsen** [comment]
The /connect resource is no longer a page. It does one of these three:
- Redirects you to Eventbrite OAuth2 page
- Redirects you to the last visited page on mojoconf.com if logged in
- Redirects you to /profile if "last visited page" is unknown.

Next: I need to handle if the user refuse to connect with Eventbrite page. Returning an exception is not good enough. https://github.com/mojoconf/MCT/blob/189e8d4a21733217e8e1c226a57e75adc12d6ade/lib/MCT/Plugin/Auth.pm#L64
