### ISSUE TITLE
Site hangs on eventbrite registration

### ISSUE THREAD

**Issue by jberger** [mojoconf/MCT#18]
[From IRC](http://irclog.perlgeek.de/mojo/2015-03-03#i_10218535):

s1037989>
FWIW, I just registered for the presentations mojoconf.org/register which redirected me to eventbrite and I filled out the form, submitted my CC details, got confirmation in my email, but the mojoconf.org/register page is stuck at a disabled "Order Now" button with a spinner on top.

**Comment by jberger** [comment]
Their demo widget seems to do the same thing

**Comment by jhthorsen** [comment]
I'm closing this, since we're not using eventbrite for registration anymore.
