### ISSUE TITLE
User Biographies

### ISSUE THREAD

**Issue by rpcme** [mojoconf/MCT#23]
I think you will be enabling users/speakers/trainers to put their biography information as part of their profile.

Af part of the site publishing we will also want the capability of displaying biography information next/around/in context of the speaker name for the training / speakers pages.

for example, if i am a user looking at training offerings, i would like to read the bio of the trainer in the context of the  training offering.

**Comment by jhthorsen** [comment]
I will add that field to the database. I will also make it so, that I fetch the bio from github when they connect.

**Comment by jhthorsen** [comment]
Example: https://www.mojoconf.com/2015/user/jhthorsen/profile

The bio can be edited in the profile page.
