### ISSUE TITLE
Add a more prominent ticket purchase link

### ISSUE THREAD

**Issue by jberger** [mojoconf/MCT#32]
@nicomen reports that he finds the "registration" link in the top corner to not be visible enough. He requests a "purchase tickets" button in the main body. I tend to agree.

**Comment by jhthorsen** [comment]
:+1:

**Comment by jhthorsen** [comment]
I think we can close this now after:
- 6078b26fe65b65adfdefdf503cd9a88e8450f526
- f08d36f6f6cf63dbb9c06e512f7b6e4e008e6ab9
- 64e6d43bcd303a54e283b1d7c08ecc7682e8cf8e
