### ISSUE TITLE
Submit talk from call for papers site does not force auth

### ISSUE THREAD

**Issue by marcusramberg** [mojoconf/MCT#40]
If you go to http://test.mojoconf.com/2015/cfp and click the big button, then fill in the form, you are sent to http://test.mojoconf.com/2015/presentations with a white screen saying "Not authorized"

**Comment by jhthorsen** [comment]
@marcusramberg: Please review https://github.com/mojoconf/MCT/pull/41.

I've also deployed #41 branch to http://test.mojoconf.com/2015. (Might be overwritten if someone tries out another branch)
