### ISSUE TITLE
Myriad Pro fail to load over https

### ISSUE THREAD

**Issue by jhthorsen** [mojoconf/MCT#45]
I'm getting this error message when changing typekit from http to https:

http://use.typekit.net/c/675120/1w;myriad-pro,2,bzN:R:n4,bzH:R:n7/d?3bb2a6e…0184b6ad71620aba7ec88e773d835a29d5c536f024b370731a6bfaacc9a05d526858a68ec6 Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by jhthorsen** [comment]
Could be because of "403 if your application has been rate limited" ..?

https://typekit.com/docs/api/errors

**Comment by tempire** [comment]
Fixed. It was a matter of allowing mojoconf.com as a registered domain in the Adobe licensing section for the usage of this non-open-source font.

**Comment by jhthorsen** [comment]
Awesome!
