### ISSUE TITLE
Globalize

### ISSUE THREAD

**Issue by rpcme** [mojoconf/MCT#49]
Currently, MCT is not globalized.  We need to be better global citizens and consider cross border terminology.

Perhaps this calls for a Mojo plugin ;)

**Comment by jhthorsen** [comment]
What does this mean? Can you provide examples? Are you talking about I18N all over the place?

**Comment by rpcme** [comment]
I am only the messenger

**Comment by jhthorsen** [comment]
Closing this due to lack of information.
