### ISSUE TITLE
Add user management for talks

### ISSUE THREAD

**Issue by jhthorsen** [mojoconf/MCT#5]
I think the missing part from eventbrite is talk management.

We need a user to be able to...
- View talks
- Edit talks
- Submit talks (change status from "new" to "submitted" or something)

Not sure about the meta info, but at least:
- Author
- Talk title
- Talk URL
- Talk abstract
- Talk duration

**Comment by jhthorsen** [comment]
See also #19.

**Comment by jhthorsen** [comment]
This is what ACT has:
- abstract
- accepted
- conf_id
- confirmed
- duration
- lightning
- room
- talk_id
- title
- track_id
- user_id

**Comment by jberger** [comment]
With #30 and #31 I think we can call this closed. Any additional features may be added later.

**Comment by jhthorsen** [comment]
:+1:
