### ISSUE TITLE
User profile link on Admin > Purchases page

### ISSUE THREAD

**Issue by rpcme** [mojoconf/MCT#59]
I would like to have items in the "Username" field be a link to their profile.  This way I can get email addresses for those who have purchased tickets.  Alternatively, either an email on the same table would work.

A feature would be to have the capability to export the table (with email, purchase price, etc) to csv/tsv format so it can be parsed/imported by another program. For example, it would be useful to have the export for email blasts.

Would like to know if there are other alternatives.

**Comment by jhthorsen** [comment]
I also add a direct email link to the purchases page, to make that step easier.
