### ISSUE TITLE
Admin > Purchases, Capture link incorrect for prod

### ISSUE THREAD

**Issue by rpcme** [mojoconf/MCT#62]
The Captured link points to test dashboard, not live dashboard.  In such case, a 404 is returned.

Please change: 

test => ""

meaning:

https://dashboard.stripe.com/test/payments/(token)
->
https://dashboard.stripe.com/payments/(token)

**Comment by jhthorsen** [comment]
This is not the best fix. I think this external_link() method should be moved into the application, so it can create a more dynamic link, dependent on the environment the application is started in.... But, I don't care enough to fix that properly now.

**Comment by rpcme** [comment]
is it more of a plugin bug then?

**Comment by jhthorsen** [comment]
"plugin bug" ? The issue is https://github.com/mojoconf/MCT/commit/c649d06f0e55a7013e76ce38ef960d1e17fca046#diff-e15a064597b678f36010375e3cb51501R7

**Comment by rpcme** [comment]
Oh! I thought maybe you were getting it from a helper in your stripe plugin.  My bad!
