### ISSUE TITLE
abstract submission has no date/time

### ISSUE THREAD

**Issue by rpcme** [mojoconf/MCT#64]
Marcus mentioned this, and I cross checked.

The presentations table doesn't have a timestamp, which means we can't track when an abstract was submitted.

If another method has been implemented to track this, please let us know.

**Comment by jhthorsen** [comment]
This is not yet merged in. I stopped working on this some weeks ago, but it was part of a grand "events" plan: https://github.com/mojoconf/MCT/pull/58/files#diff-4918f5bced2b3a1837462ae6dfeb09c7R118

**Comment by jhthorsen** [comment]
I just merged in #58 now, which replaced the "presentations" with "events" table. This table has "created", but unfortunately it has the same timestamp (when I ran the migration script).

Oh, and "events" also suffer from the same TIMESTAMP bug as mentioned in #63.
