### ISSUE TITLE
After logout, redirect to home

### ISSUE THREAD

**Issue by rpcme** [mojoconf/MCT#65]
The reason is (unless login link behavior changes):

After logout, if I click Login again, it's routing back to logout so I stay logged out.

Found in production.

**Comment by jhthorsen** [comment]
Changed it to showing a message on the landing page after logout.

![logout](https://cloud.githubusercontent.com/assets/45729/7260575/4d138cba-e86b-11e4-9822-e2ef16c04914.png)

**Comment by rpcme** [comment]
Perfect!!
